apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgCD6y9Bhu3DJxdrG8VWJD355z0y0/wmbNZwsgKDXjh+PXNW11OeqaJ17hHAz8UYyUf2SUdtvWSPWhREScQykkGuf5Loe14LS93ajBhkSYQ4RnJIYFOfnGZCNLSppEJqi9vhc3fwq6QDEEWAeLxTbmWEe7ZXHhZ5zBc0QDWL03RWqO1jhgj3sk1oWQmdKgIyqC25oGc+W3pRlLyswNb1cb6kSzsMhlcpmX9YjoxDEQXPXA5QAQw/tnomlEHcdU7Q8//qU6afpOJJ8JOzRaG2wfZ4v3o6Pq8jTqBRlUxIBCdO6xrkYVbyKtMxZMqhVbL+XAC2jQPplF6sweejmMPoV3no5RlyTmdFu6sVibh0f0BHo3WzIaHUWfUln5+OHgUgfY9AHFz3/fdpZkwH+trVbQQijgElrsRpDM1HanxRALzqWJSL/q6oyy5lYxXLXhXuvKnx5Xz1PZ9oXnG1bCsJ+SAYG8uo5AuulYiUkZL0JeOr/uNt8rhO1no4Suk+qNP27r2FG3gaQnt692nbV1KLmriEoFL4d9QIFMi05xbwNgdyOp0DiwMMeu2bSfOXAUC05amdgXdCEG0BphUxctT91qsTPv9LwXA7mrK85IDUkbzZ2U9ZY+f/Xm4BpvoSa2/3SV9AhlqB61O6RgkpuH0r8IHlP4ABXlKqTVzSoUHb2vRyc3ZeMERnuNlA1jt24n6oCzdbdLQORF3NWjiawbmYZOLTAz0jjyYHy5AsntvA9E6/iIcqgR2b8g==
    ARTIFACTORY_PASSWORD: AgCiKYEv6CILBCJk9OP1HnHouJNZxl6eWcGUyIYr4yUYt3Q9R5cRgCk+XW7u3e8KqV3zTQVh+JXn9ba0/aa7FBvVIymaqm052ZR2GRq5yKBNqrpynuxaE02Yb92EJ5ht8f7ysuRaTq2D+UI8FtqCI3y/dLtNH/4EUq1D1iWn0yjvJhb3k3O89JiTVgYIVRiy0JarvIn0PSbUvGVOWgO6ydUbMoP2VcYnFYnATepMRIbcSML4nfYrAG8zOU9Bu7CKOa2L89bwXA8/87aJst4P4Nw00WeIH6JUwBQj55aTOy2ADXP/mBwPwinVdPaIwJ6eT0rG0Ezk2F6w5RXbc3jNQ2xWX34o3PYDz6qc8t6ppAnWT03Rt0QY0cEDYsfyZ3SzX2UUwq5tZ1nFZYAZOSG9A5XNlYVHqtvabaFa9hZNgnJ6o94OayvbWdprbiPJARB5KqMF5RCP89R1RaoSBtkROPVynlONNe7Db2H+/6n/f8G1l9P6wFw/7enp6rO4fPHsdk0Db/pQjOKp4BtVcNXkdP4YVHZh1WLTiC4EZBbPqJgYH39N4bgpiKUMmYOMfSbs6TYYWigCXXUXoXdrilYCN3pekfE2B7ULm33pVix4xCx9pyQear57XYv0sV7JWXKUPphBQLDTL1AgsX7BNQQtNuTyjr+i8q1PPYCWY9ZUED5xa4TsENRrpkhRlD7oxAhf9zrTFpVhABjvShwwMJ0Lnu40XknU+Q==
    ARTIFACTORY_URL: AgAcme0EJlyikDpUzhTiMjnwLwR/Xdh3/NZ7pe4uCYcxe9L1Ku7aPzWh7FT1gSJOIP3g2W/yX1jTOSVgezAGXwyQcTtygjFyL098aHUFXCcH0cSPbp8lfT9sfsmQEavff1njTSbmTqfoC5l8YIliZYwite8DDRMEnT7jYwg25KOpI7OmGNS3wgeNLnsLvUISvYnRnnApB8IkGWbSUlWvidJ7qTBWSup14j7Vu/OFO/J9vERhFYDPvL0iyg1EHq33V+j9pSZsaLLR6quVvnZxmCeqk9zQXlUnU3tE7oa/jCEF3+eW3ct/z8IzQN8TgJGAiWm3zOHJfv4zea+oBYrta8Bp/JuJxePgyEPLxw6XlM29Es8DEgcJXsCxOQc4R81ctv+DGoCkdIquyW47FIo+EdEtEe5c0WN2HqCxo3JDmZBRgpI4idzWRYhZ7+Hp147Satmr1727rySsXBNRzyZ9343+IbQZCGqhw4nZLelz6hH++HeJCeD4DrD+7Ypq/gyy4MjLah7p1yqFap0KJLLeL39+Rpo+34bkm/HhvAMtGlXRxLcu7de63s2XqHzjwJUMMAW/O7wQty7fYoQggNWEQTaPFZGDWsQejAws9QhKOgRwDHG5HBJSJkFKXqXM2VcYS6sRlmczpH1cLCKDyhtiw4uJxNaI9pK3mmZuMfGZ5mTwHrwtE2PWvRopOf5SlyPULNarmEgcgOsuVtCgUH6hAlMDITqSQ/nFtMmRDRQL4m/2jjD0N7Q/P1tFKw==
    ARTIFACTORY_USER: AgArpt+qf1TPRbD9iWb7ul6Y3GM/zCy4h4haUlOs4nD0KL1/iPBhZ39OFvrahQHEI43T61m9TDv8P8ZdVqdkT74x8O1SKsDCtUkb1lDPiS9XraGtGlZYT3rPlu0u3tgEzG3hxZhIiJPDnUZQPf3DYur4ZEyyTvKvfWbAE6d/XMIu2yrk/WYYRvB2YR0yEBVa1AoYemRueT65HzzuFOiAdDEw6j9OZvrDZZ7/+R6FWizy3mHzRt0Eon4I+0piGw2PH+vKFDM6SrA5QaKfMkyn2cpmAHu6GF+l0lYVmXrtKA8LnopIzFtvqOefPWOJtvHtVMF5eaJlDjnNuZjn/eocMDSFGkOgLNrEb/Tsp0DgdA2fr3qqNAHtl//DRqldwwl80ZLIzDplKDujwO9M5fpWXlvQuHol5AQ6zdxdCnGiaiNITK9MlhX2Q166aSBxTklMBK7IJ1TTP6hs4aHm/19v42b/bSWjtpn2v4SeCz4KWsAPvm1mFMglo48cRfn3Da6yzac3Zjy11eS5WCUp7Gy44KtwfLDfQnA3Df6XA2PiEsR7FYQ2ItRxFwXTnWmpaVKHI7Vh+9ArhlaLBWs3LZXk4ozxo3Yq7xCUHZbbPPsoIKUsnBGPVaDHj09KIFzTEqkgIAdFIhqLe7+rvaD0+u+2eJhQEQpjHJh67WGfo4gHoHBoSAQjiocLICOwGGcfY9VdY2YFz5r2dw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2022-01-26T01:13:43Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2022-01-26T01:14:32Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

